lidofinance/lido-js-sdk

packages/web3-react/src/constants/connectors.ts, packages/web3-react/src/helpers/injected.ts, packages/web3-react/src/helpers/ua.ts, packages/web3-react/src/hooks/index.ts, packages/web3-react/src/hooks/useConnectorCoin98.ts, packages/web3-react/src/hooks/useConnectorInfo.ts, packages/web3-react/src/index.ts, packages/web3-react/test/hooks/useConnectorCoin98.test.ts
Coin98 is added to the old Stake Widget.
We need to add it to the Frontend Template and to the new version of Stake Widget.
In order to do this, we need to add it to the SDK first.
Tested using Lido Frontend Template, the wallet can be successfully connected to the widget.
=> Add Coin98 connector

packages/web3-react/src/hooks/useConnectorCoin98.ts
The address of the page from the Coin98 documentation for Firefox users was changed recently on the Coin98 side.
This PR replaces the old link with the new one.
=> Fix: use the new extension link for coin98 on firefox

packages/fetch/src/fetchWithFallbacks.ts, packages/fetch/test/fetchRPC.test.ts
BREAKING CHANGE: fetchWithFallbacks throw error for not 2xx responses
=> Fallback for not 2xx responses in fetchWithFallbacks

packages/web3-react/src/hooks/useConnectorMathWallet.ts
Mathwallet suddenly released another mobile app (MathWallet5) and declared the old app as legacy and deprecated.
So, the PR changes the links to the app.
=> Replace legacy mathwallet appstore links with links to mathwallet5

packages/web3-react/src/hooks/useConnectorInfo.ts
This PR fixes the following issue:
1. Mathwallet and Coin98 extensions are installed and turned on.
2. A user connects a MathWallet wallet.
3. A user goes to the Account modal. There is a notification: "Connected with Coin98".
It happens because the `providerName` detection is primitive.
Introducing this quick fix for now.
=> Fix(web3-react): reorder wallets in providerName function

packages/web3-react/src/helpers/index.ts, packages/web3-react/src/helpers/providerDetectors.ts, packages/web3-react/src/hooks/useConnectorInfo.ts, packages/web3-react/test/helpers/injected.test.ts, packages/web3-react/test/hooks/useAutoConnect.test.ts, packages/web3-react/test/hooks/useConnectorInfo.test.ts
Coinbase had a major update of their browser extension.
Unfortunately, there is no developer documentation for the Coinbase Wallet. But I found that the browser extension and the mobile app use the` window.ethereum.isCoinbaseWallet` property to indicate that the wallet is installed. Previously we just detected that WalletLink protocol is used, and if it is true, then Coinbase Wallet is used. But WalletLink is an open protocol, and any wallet other than Coinbase can use it. So I think it is better to detect Coinbase Wallet more explicitly.
=> Update how we detect that the Coinbase Wallet is connected

packages/web3-react/src/constants/connectors.ts, packages/web3-react/src/context/connectors.tsx, packages/web3-react/src/hooks/useConnectorInfo.ts
Previously I removed the WalletLink provider detection: https://github.com/lidofinance/lido-js-sdk/pull/31.
The reason was that only Coinbase uses it, and we can detect Coinbase wallet more specifically.
It created this minor issue: if a user connects Coinbase wallet via scanning a QR code from the mobile app, the Coinbase detection doesn't work. We can only detect that it is some WalletLink based wallet, so it can be used as a fallback.
This PR fixes this minor issue.
=> Restore WalletLink provider detection

packages/web3-react/src/hooks/useConnectorTally.ts
Tally wallet doesn't have apps for mobiles.
We need to disable its button on mobile devices.
In the current version of lido-js-sdk the disabling is done by setting `connect` to `undefined`. I plan to rework this behaviour in the future updates.
=> Disable Tally wallet on mobiles

packages/web3-react/src/constants/connectors.ts, packages/web3-react/src/context/connectors.tsx, packages/web3-react/src/hooks/index.ts, packages/web3-react/src/hooks/useConnectorWalletConnectUri.ts
This PR adds a WalletConnect connector which doesn't show the QR code modal and emits a special uri string instead.
It is required for the Ambire Wallet integration.
=> Feat(lido-js-sdk): add WalletConnectUri connector

packages/web3-react/src/hooks/useConnectorImToken.ts, packages/web3-react/src/hooks/useConnectorTally.ts
Tally devs removed their extension from FF extensions store.
We decided to redirect to https://tally.cash/community-edition/, where a user can download FF extension as .xpi file.
Another minor update: use new deeplink format for imToken, according to their docs: https://imtoken.gitbook.io/developers/products/deep-linking
=> fix(lido-js-sdk): Tally firefox link, imToken deeplink

packages/contracts/src/abi/steth.abi.json
BREAKING CHANGE: This commit only rearranges two abi elements to start a publish workflow. The actual update commit failed due to an invalid commit message.
=> feat: update steth ABI

packages/web3-react/src/hooks/useConnectorInfo.ts
This line should be "Connected with Brave Wallet"
=> Fix(web3-react): provider name for brave wallet

packages/web3-react/src/constants/connectors.ts, packages/web3-react/src/context/connectors.tsx, packages/web3-react/src/hooks/index.ts, packages/web3-react/src/hooks/useConnectorWalletConnectNoLinks.ts
This PR clones regular `WALLET_CONNECT` connector, but configures it to not have mobile links tab.
=> Add new WalletConnect connector without mobile links

packages/web3-react/src/context/connectors.tsx
Turned out that different storageId keys for WalletConnect connectors are causing issues with our autoconnect mechanism. For now, it should be `lido-walletconnect`. And it will be nice to refactor it sometime later.
=> Fix(web3-react): use the same storageId for all WC connectors

packages/web3-react/src/constants/connectors.ts, packages/web3-react/src/helpers/providerDetectors.ts, packages/web3-react/src/hooks/index.ts, packages/web3-react/src/hooks/useConnectorInfo.ts, packages/web3-react/src/hooks/useConnectorOperaWallet.ts, packages/web3-react/test/hooks/useConnectorOpera.test.ts
This PR adds a connector for the [Opera Crypto Browser Wallet](https://www.opera.com/crypto/next) and other required code.
Some docs: https://help.opera.com/en/crypto/opera-wallet-integration-guide/
=> Add Opera Crypto Wallet

packages/web3-react/src/hooks/useConnectorWalletConnect.ts, packages/web3-react/src/hooks/useConnectorWalletConnectNoLinks.ts, packages/web3-react/src/hooks/useConnectorWalletConnectUri.ts
`activate` is an async function, returns a Promise, and it should be awaited for WC connectors (at least).
This is required for the `connect` function to be properly awaited, which is required now for ZenGo wallet deeplinks integration.
=> fix(web3-react): await activate for WC

packages/web3-react/src/hooks/useConnectorInfo.ts, packages/web3-react/test/hooks/useConnectorInfo.test.ts
- Fixes an issue with a wrong detection of the connected XDEFI wallet
- Adds other wallets to ConnectorInfo, just for consistency
=> fix(web3-react): add xdefi and other wallets detectors to useConnectorInfo hook

packages/web3-react/src/hooks/useConnectorTrust.ts
This PR adds coin_id param to Trust wallet's deeplink URL according to the docs: https://developer.trustwallet.com/deeplinking#dapp-browser
This should fix the reported issue with Trust deeplink on iOS.
=> Fix(web3-react): add coin_id to trust wallet's deeplink url

packages/constants/package.json, packages/contracts/package.json, packages/fetch/package.json, packages/helpers/package.json, packages/providers/package.json, packages/react/package.json
The npm publish became broken after: https://github.com/lidofinance/lido-js-sdk/pull/119
Failed job: https://github.com/lidofinance/lido-js-sdk/actions/runs/10772387274/job/29869904950
The errors are:
```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```
Related discussions:
- https://github.com/dhoulb/multi-semantic-release/issues/129
- https://github.com/semantic-release/npm/issues/495
As suggested, setting `"workspaces-update": false`, but via `publishConfig` instead of creating `.npmrc`
Docs: [workspaces-update](https://docs.npmjs.com/cli/v10/using-npm/config#workspaces-update)
=> Attempt to fix npm release: set "workspaces-update": false

.github/workflows/deploy.yml, .npmrc, packages/constants/package.json, packages/contracts/package.json, packages/fetch/package.json, packages/helpers/package.json, packages/providers/package.json, packages/react/package.json
https://github.com/lidofinance/lido-js-sdk/pull/121 didn't help: https://github.com/lidofinance/lido-js-sdk/actions/runs/10772693898
This PR is an attempt to fix npm publish by moving the config into .npmrc
=> Attempt to fix npm release №2: use .npmrc

packages/helpers/src/etherscan.ts
* [`packages/helpers/src/etherscan.ts`](diffhunk://#diff-5bba8f5045072db472fe6ddf11773fc5aa650860e7519df14ecfab4f953906eeR22): Added `Hoodi` network to the `ETHERSCAN_PREFIX_BY_NETWORK` object.
=> feat: add Etherscan prefix for Hoodi chain

.github/CODEOWNERS
This pull request includes a small change to the `.github/CODEOWNERS` file. The change assigns all files to the `@lidofinance/lido-si` team for ownership.
=> chore: add CODEOWNERS entry for lido-si team
